/*****************/
/* miocommands.h */
/*****************/
#define MIO_COMMAND_PAUSE_RESUME	101
#define MIO_COMMAND_CLOSE		102
#define MIO_COMMAND_PRINT_FILE		103
#define MIO_COMMAND_SAVEAS_FILE		104
#define MIO_COMMAND_COPY		105
#define MIO_COMMAND_PASTE		106
#define MIO_COMMAND_SELECT_ALL		107
#define MIO_COMMAND_EXIT		108
#define MIO_COMMAND_TERMINATE		109
#define MIO_COMMAND_RERUN		110
#define MIO_COMMAND_CLOSE_ALL		111
#define MIO_COMMAND_NEW_EDITOR_WIN	112
#define MIO_COMMAND_OPEN_EDITOR_WIN	113
