/* 
From: "Chris Dennis" <Chris.Dennis@invidi.com>
To: <jikes-dev@www-126.southbury.usf.ibm.com>
Subject: RE: [Jikes-dev] MS VC++ Problem
Date: Mon, 18 Nov 2002 13:32:35 -0700
*/

/*
Here is my automatically generated config.h file for MS VC++ 6.0. It was
generated by
configure ac_cv_prog_cxx_g=no ac_cv_cxx_rtti=yes HAVE_JIKES_NAMESPACE=yes
CXX=cl CPPFLAGS="-nologo -TP -G6 -GX -GR -Ox -O2" --host=mingw32
*/

/* ------- Everything below this line was automatically generated -------- */

/* src/config.h.  Generated by configure.  */
/* src/config.h.in.  Generated from configure.in by autoheader.  */


/* This software is subject to the terms of the IBM Jikes
Compiler License Agreement available at the following URL:
http://ibm.com/developerworks/opensource/jikes.
Copyright (C) 1996, 2002 International Business Machines Corporation
and others.  All Rights Reserved.
You must accept the terms of that agreement to use this software. */


/* Defined when the compiler supports 64 bit integer math */
#define HAVE_64BIT_TYPES


/* Define to 1 if you have the <assert.h> header file. */
#define HAVE_ASSERT_H 1


/* defined if bool is a built-in C++ type */
#define HAVE_BOOL


/* known to be broken on mingwin beta 20 */
/* #undef HAVE_BROKEN_USHRT_MAX */


/* define if the compiler supports const_cast<> */
#define HAVE_CONST_CAST


/* Define to 1 if you have the <ctype.h> header file. */
#define HAVE_CTYPE_H 1


/* Define to 1 if you have the `cygwin_win32_to_posix_path_list' function.
*/
/* #undef HAVE_CYGWIN_WIN32_TO_POSIX_PATH_LIST */


/* Define to 1 if you have the <direct.h> header file. */
#define HAVE_DIRECT_H 1


/* Define to 1 if you have the <dirent.h> header file. */
/* #undef HAVE_DIRENT_H */


/* define if the compiler supports dynamic_cast<> */
#define HAVE_DYNAMIC_CAST


/* Defined if Jikes supports -encoding for input files. */
/* #undef HAVE_ENCODING */


/* Defined when the compiler would generate an error on a call to iconv with
a
   non const 2nd argument. This is a known problem on IRIX systems, as well
as
   newer GNU LIBCs. */
/* #undef HAVE_ERROR_CALL_ICONV_CONST */


/* Defined when the compiler would generate an error on a call to wcslen
with
   a non const argument. This is only known to happen on cygwin and mingwin
*/
/* #undef HAVE_ERROR_CALL_WCSLEN_CONST */


/* compiler will generate an error when discarding a const qualifier */
#define HAVE_ERROR_DISCARD_CONST


/* define if the compiler supports the explicit keyword */
#define HAVE_EXPLICIT


/* Define to 1 if you have the <float.h> header file. */
#define HAVE_FLOAT_H 1


/* use unix style mkdir(str, S_IRWXU | S_IRWXG | S_IRWXO) */
/* #undef HAVE_GLIBC_MKDIR */


/* known to be broken on Win and OS2 when compiled with ICC */
/* #undef HAVE_ICC_FP_BUGS */


/* Define to 1 if you have the <iconv.h> header file. */
/* #undef HAVE_ICONV_H */


/* Defined when Jikes is built with native floating support */
/* #undef HAVE_IEEE754 */


/* Define to 1 if you have the <inttypes.h> header file. */
/* #undef HAVE_INTTYPES_H */


/* Define Jikes classes in a C++ namespace */
/* #undef HAVE_JIKES_NAMESPACE */


/* use unix style mkdir(str, S_IRWXU) */
/* #undef HAVE_LIBC5_MKDIR */


/* Define to 1 if you have the `iconv' library (-liconv). */
/* #undef HAVE_LIBICONV */


/* Define to 1 if you have the `icu-uc' library (-licu-uc). */
/* #undef HAVE_LIBICU_UC */


/* Define to 1 if you have the `m' library (-lm). */
/* #undef HAVE_LIBM */


/* Define to 1 if you have the <limits.h> header file. */
#define HAVE_LIMITS_H 1


/* Define to 1 if you have the <locale.h> header file. */
#define HAVE_LOCALE_H 1


/* use mac style mkdir(str,0) from <stat.mac.h> */
/* #undef HAVE_MAC_MKDIR */


/* Define to 1 if you have the <math.h> header file. */
#define HAVE_MATH_H 1


/* define if the compiler supports member constants */
/* #undef HAVE_MEMBER_CONSTANTS */


/* Define to 1 if you have the <memory.h> header file. */
#define HAVE_MEMORY_H 1


/* Define to 1 if you have the `mkdir' function. */
#define HAVE_MKDIR 1


/* define if the compiler implements namespaces */
#define HAVE_NAMESPACES 1


/* compiler has ostream << const unsigned char * */
#define HAVE_OSTREAM_CONST_UNSIGNED_CHAR_PTR


/* defined if running on a system with dos style paths */
#define HAVE_PATHNAME_STYLE_DOS


/* define if the compiler supports reinterpret_cast<> */
#define HAVE_REINTERPRET_CAST


/* define if the compiler supports Run-Time Type Identification */
#define HAVE_RTTI


/* define if the compiler supports static_cast<> */
#define HAVE_STATIC_CAST


/* define if the compiler supports ISO C++ standard library */
#define HAVE_STD


/* Define to 1 if you have the <stdint.h> header file. */
/* #undef HAVE_STDINT_H */


/* Define to 1 if you have the <stdio.h> header file. */
#define HAVE_STDIO_H 1


/* Define to 1 if you have the <stdlib.h> header file. */
#define HAVE_STDLIB_H 1


/* Define to 1 if you have the <strings.h> header file. */
/* #undef HAVE_STRINGS_H */


/* Define to 1 if you have the <string.h> header file. */
#define HAVE_STRING_H 1


/* Define to 1 if you have the <sys/cygwin.h> header file. */
/* #undef HAVE_SYS_CYGWIN_H */


/* Define to 1 if you have the <sys/stat.h> header file. */
#define HAVE_SYS_STAT_H 1


/* Define to 1 if you have the <sys/types.h> header file. */
#define HAVE_SYS_TYPES_H 1


/* Define to 1 if you have the <time.h> header file. */
#define HAVE_TIME_H 1


/* Define to 1 if you have the <unistd.h> header file. */
/* #undef HAVE_UNISTD_H */


/* Use visual C++ version of set_new_handler */
#define HAVE_VCPP_SET_NEW_HANDLER


/* Define to 1 if you have the <wchar.h> header file. */
#define HAVE_WCHAR_H 1


/* Define to 1 if you have the `wcscat' function. */
#define HAVE_WCSCAT 1


/* Define to 1 if you have the `wcscmp' function. */
#define HAVE_WCSCMP 1


/* Define to 1 if you have the `wcscpy' function. */
#define HAVE_WCSCPY 1


/* Define to 1 if you have the `wcslen' function. */
#define HAVE_WCSLEN 1


/* Define to 1 if you have the `wcsncmp' function. */
#define HAVE_WCSNCMP 1


/* Define to 1 if you have the `wcsncpy' function. */
#define HAVE_WCSNCPY 1


/* use win32 style mkdir(str) from <direct.h> */
#define HAVE_WIN32_MKDIR


/* Define to 1 if you have the <windows.h> header file. */
#define HAVE_WINDOWS_H 1


/* Defined when the wint_t type is supported */
#define HAVE_WINT_T


/* Enable internal compiler debugging */
/* #undef JIKES_DEBUG */


/* Define this to the name of the unicode encoding that is the same size as
   your wchar_t. See also the following entry for byte swapping. */
/* #undef JIKES_ICONV_ENCODING */


/* Define this if the encoding specified above does not match your
platform's
   native endianness. */
/* #undef JIKES_ICONV_NEEDS_BYTE_SWAP */


/* Used to test results of stat call to see if it is a directory */
#define JIKES_STAT_S_IFDIR _S_IFDIR


/* A string to indicate the release of jikes: Version 1.17 - 27 Sept 2002 */
#define JIKES_VERSION_STRING "Version post1.17-CVS - 12 November 2002"


/* Name of package */
#define PACKAGE "jikes"


/* Define to the address where bug reports for this package should be sent.
*/
#define PACKAGE_BUGREPORT ""


/* Define to the full name of this package. */
#define PACKAGE_NAME "jikes"


/* Define to the full name and version of this package. */
#define PACKAGE_STRING "jikes 1.17a"


/* Define to the one symbol short name of this package. */
#define PACKAGE_TARNAME "jikes"


/* Define to the version of this package. */
#define PACKAGE_VERSION "1.17a"


/* used to seperate elements on the PATH */
#define PATH_SEPARATOR ';'


/* The size of a `char', as computed by sizeof. */
/* #undef SIZEOF_CHAR */


/* The size of a `int', as computed by sizeof. */
/* #undef SIZEOF_INT */


/* The size of a `long', as computed by sizeof. */
/* #undef SIZEOF_LONG */


/* The size of a `long long', as computed by sizeof. */
/* #undef SIZEOF_LONG_LONG */


/* The size of a `short', as computed by sizeof. */
/* #undef SIZEOF_SHORT */


/* The size of a `signed', as computed by sizeof. */
#define SIZEOF_SIGNED 4


/* The size of a `signed char', as computed by sizeof. */
#define SIZEOF_SIGNED_CHAR 1


/* The size of a `signed int', as computed by sizeof. */
/* #undef SIZEOF_SIGNED_INT */


/* The size of a `signed long', as computed by sizeof. */
#define SIZEOF_SIGNED_LONG 4


/* The size of a `signed long long', as computed by sizeof. */
#define SIZEOF_SIGNED_LONG_LONG 0


/* The size of a `signed short', as computed by sizeof. */
#define SIZEOF_SIGNED_SHORT 2


/* The size of a `unsigned', as computed by sizeof. */
#define SIZEOF_UNSIGNED 4


/* The size of a `unsigned char', as computed by sizeof. */
#define SIZEOF_UNSIGNED_CHAR 1


/* The size of a `unsigned int16_t', as computed by sizeof. */
#define SIZEOF_UNSIGNED_INT16_T 0


/* The size of a `unsigned int32_t', as computed by sizeof. */
#define SIZEOF_UNSIGNED_INT32_T 0


/* The size of a `unsigned int64_t', as computed by sizeof. */
#define SIZEOF_UNSIGNED_INT64_T 8


/* The size of a `unsigned int8_t', as computed by sizeof. */
#define SIZEOF_UNSIGNED_INT8_T 0


/* The size of a `unsigned long', as computed by sizeof. */
/* #undef SIZEOF_UNSIGNED_LONG */


/* The size of a `unsigned long long', as computed by sizeof. */
/* #undef SIZEOF_UNSIGNED_LONG_LONG */


/* The size of a `unsigned short', as computed by sizeof. */
#define SIZEOF_UNSIGNED_SHORT 2


/* The size of a `unsigned __int16', as computed by sizeof. */
/* #undef SIZEOF_UNSIGNED___INT16 */


/* The size of a `unsigned __int32', as computed by sizeof. */
/* #undef SIZEOF_UNSIGNED___INT32 */


/* The size of a `unsigned __int64', as computed by sizeof. */
/* #undef SIZEOF_UNSIGNED___INT64 */


/* The size of a `unsigned __int8', as computed by sizeof. */
/* #undef SIZEOF_UNSIGNED___INT8 */


/* The size of a `wchar_t', as computed by sizeof. */
/* #undef SIZEOF_WCHAR_T */


/* The size of a `__int16', as computed by sizeof. */
/* #undef SIZEOF___INT16 */


/* The size of a `__int32', as computed by sizeof. */
/* #undef SIZEOF___INT32 */


/* The size of a `__int64', as computed by sizeof. */
#define SIZEOF___INT64 8


/* The size of a `__int8', as computed by sizeof. */
/* #undef SIZEOF___INT8 */


/* Define to 1 if you have the ANSI C header files. */
#define STDC_HEADERS 1


/* quick hack to use UNIX file system, fixme */
/* #undef UNIX_FILE_SYSTEM */


/* Version number of package */
#define VERSION "1.17a"


/* quick hack to use Win32 file system, fixme */
#define WIN32_FILE_SYSTEM


/* Define to 1 if your processor stores words with the most significant byte
   first (like Motorola and SPARC, unlike Intel and VAX). */
/* #undef WORDS_BIGENDIAN */


/* If not already defined, then define as a datatype of *exactly* 16 bits.
*/
#define int16_t signed short


/* If not already defined, then define as a datatype of *exactly* 32 bits.
*/
#define int32_t signed


/* If not already defined, then define as a datatype of *exactly* 64 bits.
*/
#define int64_t __int64


/* If not already defined, then define as a datatype of *exactly* 8 bits. */
#define int8_t signed char


/* If not already defined, then define as a datatype of *exactly* 16 bits.
*/
#define uint16_t unsigned short


/* If not already defined, then define as a datatype of *exactly* 32 bits.
*/
#define uint32_t unsigned


/* If not already defined, then define as a datatype of *exactly* 64 bits.
*/
#define uint64_t unsigned int64_t


/* If not already defined, then define as a datatype of *exactly* 8 bits. */
#define uint8_t unsigned char
