/***************/
/* jsdialogs.h */
/***************/

// JSMain - Error Messages
#define IDS_ERROR_BOX_TITLE		1001
#define IDS_NO_JAVA_DLL_SUPPLIED	1002
#define IDS_NO_CLASSPATH_SUPPLIED	1003
#define IDS_NO_CLASSNAME_SUPPLIED	1004
#define IDS_NO_DIRECTORY_SUPPLIED	1005
#define IDS_UNABLE_TO_LOAD_LIBRARY	1006
#define IDS_UNABLE_TO_FIND_PROC		1007
#define IDS_UNABLE_TO_FIND_CLASS	1008
#define IDS_UNABLE_TO_FIND_METHOD	1009
#define IDS_CANT_CHANGE_DIR		1010
#define IDS_MALFORMED_OPTION		1011
#define IDS_OUT_OF_MEM_FOR_STRING	1012
#define IDS_ALLOC_CONSOLE_FAILED	1013
#define IDS_UNKNOWN_OPTION		1014
#define IDS_JVM_CREATION_FAILED		1015
#define IDS_CANT_LOAD_LIB		1016
#define IDS_UNEXPECTED_PATH		1017
#define IDS_UNABLE_TO_CREATE_THREAD	1018
#define IDS_CANT_FREE_MEMORY		1019
#define IDS_CANT_OPEN_FILE		1020
#define IDS_CANT_OPEN_FILE_FOR_READ	1021
#define IDS_CANT_OPEN_FILE_FOR_WRITE	1022
#define IDS_BAD_FULLSCREEN_OPTION	1023
#define IDS_BAD_TEXTROWS_OPTION		1024
#define IDS_BAD_TEXTCOLS_OPTION		1025
#define IDS_BAD_TEXTFONTSIZE_OPTION	1026
#define IDS_BAD_CARETWIDTH_OPTION	1027
#define IDS_BAD_LOGGING_OPTION		1028
#define IDS_BAD_LOGGINGWINDOWS_OPTION	1029
#define IDS_BAD_DIALOGFONTSIZE_OPTION	1030
#define IDS_BAD_SPACESPERTAB_OPTION	1031
#define IDS_BAD_VERIFYDB_OPTION		1032
#define IDS_UNABLE_TO_FIND_STRING_CLASS	1033
#define IDS_UNABLE_TO_CREATE_ARGS_ARRAY	1034
#define IDS_UNABLE_TO_CREATE_ARG_STRING	1035
#define IDS_UNABLE_TO_OPEN_PRINT_SIGNAL	1036
#define IDS_UNABLE_TO_WRITE_PRINT_JOB	1037
#define IDS_UNABLE_TO_OPEN_EXCEPTION_SIGNAL	1038
#define IDS_UNABLE_TO_WRITE_EXCEPTION	1039
#define IDS_LOG_FILE_WRITE_FAILED	1040
#define IDS_LOG_FILE_WRITE_FAILED1	1041
#define IDS_LOG_FILE_FLUSH_FAILED	1042
#define IDS_UNABLE_TO_OPEN_FAIL_MESSAGE_SIGNAL	1043
#define IDS_UNABLE_TO_WRITE_FAIL_MESSAGE	1044
#define IDS_BAD_RUN13_OPTION		1045

// From JSCon - Error Messages
#define IDS_CREATEBRUSHFAIL		2001
#define IDS_REGISTERCLASSFAIL		2002
#define IDS_COMMAND_NOT_PROCESSED	2003
#define IDS_BADWINDOWTYPE		2004
#define IDS_GETWINDOWLONGFAIL		2005
#define IDS_NO_MEM_FOR_RESIZE		2006
#define IDS_NO_RESIZE			2007
#define IDS_CREATEFONTFAIL		2008
#define IDS_CREATEWINDOWFAIL		2009
#define IDS_LOCATER_LOOPING_INFINITELY	2010

// From EdGUI - Error Messages
#define IDS_LOADSTRINGFAIL		2101
#define IDS_FORMATMESSAGEFAIL		2102

// Window Titles for Message Box
#define IDS_STOP_PROGRAM_TITLE		3001
#define IDS_EMPTY_FILE_TITLE		3002
#define IDS_COPY_FAILED_TITLE		3003
#define IDS_FILE_DIALOG_ERROR_TITLE	3004

// Window Messages for Message Box
#define IDS_STOP_PROGRAM		4001
#define IDS_NOTHING_TO_SAVE		4002
#define IDS_NOTHING_TO_PRINT		4003
#define IDS_COPY_FAILED_MESSAGE		4004
#define IDS_LINEDBVERIFY_FAILED		4005
#define IDS_FILE_DIALOG_ERROR_MESSAGE	4006
#define IDS_LINEDBVERIFY1_FAILED	4007

// Button names
#define IDS_PAUSE_BUTTON		5001
#define IDS_CLOSE_BUTTON		5002
#define IDS_PRINT_BUTTON		5003
#define IDS_SAVE_BUTTON			5004
#define IDS_COPY_BUTTON			5005
#define IDS_PASTE_BUTTON		5006
#define IDS_RESUME_BUTTON		5007

#define IDS_PAUSE_BUTTON_LONG		5021
#define IDS_CLOSE_BUTTON_LONG		5022
#define IDS_PRINT_BUTTON_LONG		5023
#define IDS_SAVE_BUTTON_LONG		5024
#define IDS_COPY_BUTTON_LONG		5025
#define IDS_PASTE_BUTTON_LONG		5026
#define IDS_RESUME_BUTTON_LONG		5027

// Other Strings
#define IDS_CONSOLE_WINDOW_NAME		6001
#define IDS_CONSOLETEXT_WINDOW_NAME	6002
#define IDS_JSTOP_WINDOW_NAME		6003
#define IDS_RAISED_FRAME_WINDOW_NAME	6004

#define IDS_DIALOG_FONT_NAME		7001

// Accelerators
#define CONSOLE_WINDOW_ACCELERATOR	 500

// Icons
#define APP_ICON			   1
#define APP_SMALL_ICON			   2
#define RUN_ICON			  11
#define RUN_SMALL_ICON			  12

/*
//
// String table identifiers
//

//
// Ready File and Directory Names
//
    
// Directories
#define IDS_SUPPORT_DIR			4001
#define IDS_INI_DIR			4002
#define IDS_ADDITIONAL_CLASSES_DIR	4003
#define IDS_JVM				4004
#define IDS_JAVA_BIN			4005
#define IDS_JAVA_LIB			4006
#define IDS_READY_BIN			4007

// Files (INI)
#define IDS_ADMIN_PREF			4101
#define IDS_USER_PREF			4102
#define IDS_NEW_MENU			4103
#define IDS_INSERT_MENU			4104
#define IDS_HTML_BOILERPLATE		4105
#define IDS_RECENT_FILES		4106
#define IDS_PANIC_LOG_FILE		4107
#define IDS_LOG_FILE			4108
#define IDS_MEMORY_LEAK_FILE		4109

// Class Library
#define IDS_JAVA_CLASS_LIBRARY		4151
#define IDS_JAVA_EXTRA_CLASSES_DIR	4152
#define IDS_JAVA_MATH_JAR		4153
#define IDS_JAVA_RT_JAR			4154
#define IDS_JAVA_I18N_JAR		4155

// Java Executors
#define IDS_JAVA_EXECUTOR		4201
#define IDS_JAVA_APPLET_RUNNER		4202
#define IDS_READY_CONSOLE_RUNNER	4203

//    
// Window names
//
#define IDS_APPLICATION_NAME		5001
#define IDS_EDIT_WINDOW_NAME		5002
#define IDS_STATUS_WINDOW_NAME		5003
#define IDS_TEXTDISPLAY_WINDOW_NAME	5004
#define IDS_TEXTDISPLAY_MDI_WINDOW_NAME	5005
#define IDS_BBAR_WINDOW_NAME		5006
#define IDS_SUNKEN_FRAME_WINDOW_NAME	5008
#define IDS_SPLASH_WINDOW_NAME		5009
#define IDS_EDIT_MDI_FRAME_WINDOW_NAME	5010
#define IDS_CONSOLE_WINDOW_NAME		5011
#define IDS_CONSOLETEXT_WINDOW_NAME	5012

// Parameters to EdFail_Warn/Fatal
#define IDS_CREATEBRUSHFAIL		6001
#define IDS_LOADSTRINGFAIL		6002
#define IDS_REGISTERCLASSFAIL		6003
#define IDS_CREATEWINDOWFAIL		6004
#define IDS_DDEINITIALIZEFAIL		6005
#define IDS_DDECREATESTRINGHANDLEFAIL	6006
#define IDS_DDENAMESERVICEFAIL		6007
#define IDS_LOADACCELERATORSFAIL	6008
// 6009 No longer needed
#define IDS_CREATEFONTFAIL		6010
#define IDS_REGISTERWINDOWMESSAGEFAIL	6011
#define IDS_OUTOFMEMORY			6012
#define IDS_GETDATEFORMATFAIL		6013
#define IDS_GETTIMEFORMATFAIL		6014
#define IDS_GETWINDOWLONGFAIL		6015
#define IDS_BADWINDOWTYPE		6016
#define IDS_UNEXPECTED_CHAR		6017
// 6018 No longer needed
#define IDS_GETDLGITEMFAIL		6019
#define IDS_CREATECOMPATIBLEDCFAIL	6020
#define IDS_CREATECOMPATIBLEBITMAPFAIL	6021
#define IDS_CANTFINDMARK		6022
#define IDS_UNEXPECTED_WINDOW_KIND	6024
#define IDS_WINDOW_NOT_FOUND		6025
#define IDS_COMMAND_NOT_PROCESSED	6026
#define IDS_RECENT_FILE_NOT_FOUND	6027
#define IDS_CANT_REVERT_NO_NAME_FILE	6028
#define IDS_NO_MEM_FOR_RESIZE		6030
#define IDS_NO_RESIZE			6031
#define IDS_NO_MENU_NAME		6032
#define IDS_NO_MEM_FOR_MENU		6033
#define IDS_NO_TEXT_FOR_MEM_ENTRY	6034
#define IDS_OUTPUTCHAR_OF_SPACE		6036
#define IDS_NEW_SKELETON_NOT_FOUND	6037
#define IDS_READFROMPIPEFAIL		6038
#define IDS_PEEKFROMPIPEFAIL		6039
#define IDS_READFROMPIPESHORT		6040
#define IDS_MALFORMEDERROR		6041
#define IDS_ILLEGAL_INSTRUCTION_SIGNAL	6042
#define IDS_FLOATING_POINT_EXCEPTION_SIGNAL	6043
#define IDS_GENERAL_PROTECTION_FAULT_SIGNAL	6044
#define IDS_FREECONSOLEFAIL		6045
#define IDS_ALLOCCONSOLEFAIL		6046
#define IDS_HTMLBOILERMISSINGFAIL	6047
#define IDS_HTMLBOILERREADFAIL		6048

// Parameters to EdWin_Show{Bold}1

// Menu Item Names - New
#define IDS_NEW_MENU_ITEM		6400

// Menu Item Names - Undo
#define IDS_NORMAL_UNDO			6500
#define IDS_UNDO_BASE			6500
#define IDS_UNDO_TYPING			6501
#define IDS_UNDO_CUT			6502
#define IDS_UNDO_PASTE			6503
#define IDS_UNDO_CLEAR			6504
#define IDS_UNDO_REVERT			6505
#define IDS_UNDO_COMMENT		6506
#define IDS_UNDO_UNCOMMENT		6507
#define IDS_UNDO_INSERT			6508
#define IDS_UNDO_INDENT			6509
#define IDS_UNDO_REPLACE		6510
#define IDS_UNDO_REPLACE_ALL		6511
#define IDS_REDO_BASE			6600
#define IDS_REDO_TYPING			6601
#define IDS_REDO_CUT			6602
#define IDS_REDO_PASTE			6603
#define IDS_REDO_CLEAR			6604
#define IDS_REDO_REVERT			6605
#define IDS_REDO_COMMENT		6606
#define IDS_REDO_UNCOMMENT		6607
#define IDS_REDO_INSERT			6608
#define IDS_REDO_INDENT			6609
#define IDS_REDO_REPLACE		6610
#define IDS_REDO_REPLACE_ALL		6611

// Menu Item Names - Run
#define IDS_RUN_MENU_ITEM		6700
#define IDS_RUN_MAIN_MENU_ITEM		6701
#define IDS_COMPILE_MENU_ITEM		6702
#define IDS_COMPILE_MAIN_MENU_ITEM	6703

//
// Status Messages
//
#define IDS_NORMAL_UNDO_STATUS		6800
#define IDS_UNDO_BASE_STATUS		6800
#define IDS_UNDO_TYPING_STATUS		6801
#define IDS_UNDO_CUT_STATUS		6802
#define IDS_UNDO_PASTE_STATUS		6803
#define IDS_UNDO_CLEAR_STATUS		6804
#define IDS_UNDO_REVERT_STATUS		6805
#define IDS_UNDO_COMMENT_STATUS		6806
#define IDS_UNDO_UNCOMMENT_STATUS	6807
#define IDS_UNDO_INSERT_STATUS		6808
#define IDS_UNDO_INDENT_STATUS		6809
#define IDS_UNDO_REPLACE_STATUS		6810
#define IDS_UNDO_REPLACE_ALL_STATUS	6811
#define IDS_REDO_BASE_STATUS		6900
#define IDS_REDO_TYPING_STATUS		6901
#define IDS_REDO_CUT_STATUS		6902
#define IDS_REDO_PASTE_STATUS		6903
#define IDS_REDO_CLEAR_STATUS		6904
#define IDS_REDO_REVERT_STATUS		6905
#define IDS_REDO_COMMENT_STATUS		6906
#define IDS_REDO_UNCOMMENT_STATUS	6907
#define IDS_REDO_INSERT_STATUS		6908
#define IDS_REDO_INDENT_STATUS		6909
#define IDS_REDO_REPLACE_STATUS		6910
#define IDS_REDO_REPLACE_ALL_STATUS	6911
#define IDS_ERRORS_AND_WARNINGS_STATUS	6912
#define IDS_ERRORS_AND_WARNING_STATUS	6913
#define IDS_ERROR_AND_WARNINGS_STATUS	6914
#define IDS_ERROR_AND_WARNING_STATUS	6915
#define IDS_ERRORS_STATUS		6916
#define IDS_ERROR_STATUS		6917
#define IDS_WARNINGS_STATUS		6918
#define IDS_WARNING_STATUS		6919
#define IDS_ERRORS_AND_WARNINGS_MF_STATUS	6920
#define IDS_ERRORS_AND_WARNING_MF_STATUS	6921
#define IDS_ERROR_AND_WARNINGS_MF_STATUS	6922
#define IDS_ERROR_AND_WARNING_MF_STATUS	6923
#define IDS_ERRORS_MF_STATUS		6924
#define IDS_ERROR_MF_STATUS		6925
#define IDS_WARNINGS_MF_STATUS		6926
#define IDS_WARNING_MF_STATUS		6927
#define IDS_SUCCESSFUL_COMPILE_STATUS	6928
#define IDS_FIX_MAIN_STATUS		6929
#define IDS_FLOAT_MAIN_STATUS		6930


// The font names for dialogs

// The Line/Col position string    
#define IDS_SHORT_POSITION_STRING	7002
#define IDS_LONG_POSITION_STRING	7003

// The name for an unnamed window
#define IDS_UNNAMED_WINDOW_TITLE	7101

// The name for the hidden java console
#define IDS_JAVA_CONSOLE_NAME		7102

// The strings used in the EdFail_Warn/Fatal procedure
#define IDS_FATALWINDOWTITLE		8001
#define IDS_WARNWINDOWTITLE		8002
#define IDS_FAILPREAMBLE		8003
#define IDS_FAILREASONNOTFOUND		8004
#define IDS_FAILREASONFOUND		8005
#define IDS_FAILWINDOWSERROR		8006
#define IDS_FAILFILELINE		8007
#define IDS_FAILSAVEFILE		8008

// Parameters to EdGUI_Message1 (Dialog Box Titles)
#define IDS_INIT_FAILURE_TITLE		8101
#define IDS_CMD_LINE_FAILURE_TITLE	8102
#define IDS_CMD_LINE_HELP_TITLE		8103
#define IDS_CMD_LINE_ERR_TITLE		8104
#define IDS_COPY_FAILED_TITLE		8105
#define IDS_OUT_OF_TEXT_MEM_TITLE	8106
#define IDS_FILE_OPEN_FAILED_TITLE	8107
#define IDS_INDENT_FAILED_TITLE		8108
#define IDS_PRINT_ERROR_TITLE		8109
#define IDS_WARNING_TITLE		8110
#define IDS_STARTUP_ERROR_TITLE		8111
#define IDS_FILE_SAVE_DISALLOWED_TITLE	8112
#define IDS_FILE_OPEN_DISALLOWED_TITLE	8113
#define IDS_PREF_ERROR_TITLE		8114
#define IDS_EMPTY_FILE_TITLE		8115
#define IDS_NO_SELECTION_TITLE		8116
#define IDS_NOT_CHANGED_TITLE		8117
#define IDS_NO_ASSOC_FILE_TITLE		8118
#define IDS_NO_MAIN_PROG_TITLE		8119
#define IDS_NO_UNDO_TITLE		8120
#define IDS_NO_CLIPBOARD_TITLE		8121
#define IDS_NO_SEARCH_TEXT_TITLE	8122
#define IDS_ADMIN_TITLE			8123
#define IDS_ERRORS_FOUND_TITLE		8124
#define IDS_RUN_ERROR_TITLE		8125
#define IDS_CLASS_NAME_TITLE		8126
#define IDS_FILE_NAME_COLLISION_TITLE	8127
#define IDS_ILLEGAL_FILE_NAME_TITLE	8128
#define IDS_STOP_PROGRAM_TITLE		8129
#define IDS_UNIMPL_FEATURE_TITLE	8130
#define IDS_CANT_START_JAVA_TITLE	8131
#define IDS_NO_CLASSLIB_TITLE		8132
#define IDS_COMPILATION_ERROR_TITLE	8133


// Parameters to EdGUI_Message1 (Dialog Box Messages) (in FormatMessage format)
#define IDS_CONFIRM_QUIT_MESSAGE	8201
#define IDS_SAVE_CHANGES_MESSAGE	8202
#define IDS_INIT_FAILURE_MESSAGE	8203
#define IDS_CMD_LINE_FAILURE_MESSAGE	8204
#define IDS_UNABLE_TO_OPEN_WINDOW	8205
#define IDS_CMD_LINE_HELP_MESSAGE	8206
#define IDS_UNKNOWN_CMD_LINE_OPTION	8207
#define IDS_COPY_FAILED_MESSAGE		8208
#define IDS_OUT_OF_TEXT_MEM_MESSAGE	8209
#define IDS_FILE_NOT_FOUND		8210
#define IDS_FILE_OPEN_FAILED_MESSAGE	8211
#define IDS_INDENT_OUT_OF_MEM		8212
#define IDS_NO_MEM_FOR_UNDO_MESSAGE	8213
#define IDS_REVERT_MESSAGE		8214
#define IDS_NO_TWO_UP_LANDSCAPE		8215
#define IDS_CANT_CHANGE_PREFS		8216
#define IDS_NO_WRITE_PREFS		8217
#define IDS_CANT_FIND_ENVIRONMENT_VAR	8218
#define IDS_CANT_CHANGE_STARTUP_DIR	8219
#define IDS_UNTERMINATED_ENV_VAR	8220
#define IDS_FILE_ONLY_IN_HOME		8221
#define IDS_NETWORK_DRIVE_NOT_PERMITTED	8222
#define IDS_DRIVE_NOT_PERMITTED		8223
#define IDS_NOT_A_NUMBER		8224
#define IDS_CANT_CLOSE_FILE		8225
#define IDS_BAD_PREF1			8226
#define IDS_BAD_PREF2			8227
#define IDS_PREF_NEEDS_INT		8228
#define IDS_PREF_NEEDS_BOOL		8229
#define IDS_UNKNOWN_PROPERTY		8230
#define IDS_NOTHING_TO_SAVE		8231
#define IDS_NO_SELECTION_TO_SAVE	8232
#define IDS_FILE_HAS_NOT_BEEN_CHANGED	8233
#define IDS_FILE_HAS_NO_ASSOCIATED_FILE	8234
#define IDS_NOTHING_TO_PRINT		8235
#define IDS_NOTHING_TO_FIX_AS_MAIN	8236
#define IDS_NO_MAIN_PROG_SELECTED	8237
#define IDS_NOTHING_TO_UNDO		8238
#define IDS_NO_SELECTION_TO_CUT		8239
#define IDS_NO_SELECTION_TO_COPY	8240
#define IDS_NO_TEXT_IN_CLIPBOARD	8241
#define IDS_NOTHING_TO_SELECT		8242
#define IDS_NO_SELECTION_TO_COMMENT	8243
#define IDS_NO_SELECTION_TO_UNCOMMENT	8244
#define IDS_NOTHING_TO_INDENT		8245
#define IDS_NOTHING_TO_SEARCH		8246
#define IDS_NO_SEARCH_TEXT		8247
#define IDS_NOTHING_TO_GOTO		8248
#define IDS_NOTHING_TO_RUN		8249
#define IDS_ADMIN_MESSAGE		8250
#define IDS_ADMIN_FAIL_MESSAGE		8251
#define IDS_ERRORS_AND_WARNINGS_FOUND	8252
#define IDS_ERRORS_AND_WARNING_FOUND	8253
#define IDS_ERROR_AND_WARNINGS_FOUND	8254
#define IDS_ERROR_AND_WARNING_FOUND	8255
#define IDS_ERRORS_FOUND		8256
#define IDS_ERROR_FOUND			8257
#define IDS_WARNINGS_FOUND		8258
#define IDS_WARNING_FOUND		8259
#define IDS_ERRORS_AND_WARNINGS_MF_FOUND 8260
#define IDS_ERRORS_AND_WARNING_MF_FOUND	8261
#define IDS_ERROR_AND_WARNINGS_MF_FOUND	8262
#define IDS_ERROR_AND_WARNING_MF_FOUND	8263
#define IDS_ERRORS_MF_FOUND		8264
#define IDS_ERROR_MF_FOUND		8265
#define IDS_WARNINGS_MF_FOUND		8266
#define IDS_WARNING_MF_FOUND		8267
#define IDS_WARNINGS_NO_ASK_FOUND	8268
#define IDS_WARNING_NO_ASK_FOUND	8269
#define IDS_WARNINGS_MF_NO_ASK_FOUND	8270
#define IDS_WARNING_MF_NO_ASK_FOUND	8271
#define IDS_NOT_A_JAVA_FILE		8272
#define IDS_FILE_DOES_NOT_END_IN_JAVA	8273
#define IDS_CLASS_NAME_BAD_STYLE	8274
#define IDS_FILE_NAME_COLLISION		8275
#define IDS_USE_CLASS_NAME		8276
#define IDS_ILLEGAL_FILE_NAME		8277
#define IDS_STOP_PROGRAM		8278
#define IDS_UNIMPLEMENTED_FEATURE	8279
#define IDS_CANT_START_JAVA	    	8280
#define IDS_NO_CLASSLIB			8281
#define IDS_USE_STRING			8282
#define IDS_RTF_MUST_BE_JAVA		8283
#define IDS_ILLEGAL_RTF_FILE_NAME	8284
#define IDS_NOT_JAVA_CLASS_TITLE	8285


// Error messages for Get classname
#define IDS_BAD_FIRST_CLASSNAME_CHAR	8601
#define IDS_BAD_FOLLOW_CLASSNAME_CHAR	8602
#define IDS_LOWER_FIRST_CLASSNAME_CHAR	8603

#define IDS_CLASSNAMEHOLDER		8701
#define IDS_XSIZEHOLDER			8702
#define IDS_YSIZEHOLDER			8703

// Button names
#define IDS_RUN_BUTTON			9001
#define IDS_INDENT_BUTTON		9002
#define IDS_SAVE_BUTTON			9003
#define IDS_PRINT_BUTTON		9004
#define IDS_CUT_BUTTON			9005
#define IDS_COPY_BUTTON			9006
#define IDS_PASTE_BUTTON		9007
#define IDS_FIND_BUTTON			9008
#define IDS_FIND_NEXT_BUTTON		9009
#define IDS_REPLACE_BUTTON		9010
#define IDS_STOP_BUTTON			9011

#define IDS_RUN_BUTTON_LONG		9021
#define IDS_INDENT_BUTTON_LONG		9022
#define IDS_SAVE_BUTTON_LONG		9023
#define IDS_PRINT_BUTTON_LONG		9024
#define IDS_CUT_BUTTON_LONG		9025
#define IDS_COPY_BUTTON_LONG		9026
#define IDS_PASTE_BUTTON_LONG		9027
#define IDS_FIND_BUTTON_LONG		9028
#define IDS_FIND_NEXT_BUTTON_LONG	9029
#define IDS_REPLACE_BUTTON_LONG		9030
#define IDS_STOP_BUTTON_LONG		9031

//
// Dialog parts
//
#define EDIT_WINDOW_ACCELERATOR		1001
#define EDIT_WINDOW_MENUS		1002
#define GOTO_LINE_DIALOG		1003
#define EDIT_INIT_SINGLE_WINDOW_MENUS	1004
#define FIND_REPLACE_DIALOG_ACCELERATOR	1005
#define READY_PRINT_DIALOG		1006
#define GET_CLASSNAME_DIALOG		1007
#define CONSOLE_WINDOW_ACCELERATOR	1008
#define PROGRAM_TYPE_1_DIALOG		1009
#define PROGRAM_TYPE_2_DIALOG		1010
#define PROGRAM_TYPE_3_DIALOG		1011
#define PROGRAM_TYPE_4_DIALOG		1012
#define UNKNOWN_COMCTL_VERSION		1013
#define BAD_COMCTL_VERSION		1014
#define GET_APPLET_SIZE_DIALOG		1015

#define	GOTO_EDITBOX			301
#define CLASSNAME_EDITBOX		302
#define CLASSNAME_WARNING_LABEL		303
#define APPLICATION_BUTTON		304
#define APPLET_BUTTON			305
#define XSIZE_EDITBOX			306
#define YSIZE_EDITBOX			307

// Administrative preferences dialog box
#define PREF_STARTUPDIR			401
#define PREF_CHANGEUSERNAME		402
#define PREF_ENTERADVANCED		403
#define PREF_ONLYSTARTUPDIR		404
#define PREF_ALLOWEDDRIVES		405
#define PREF_ALLOWEDDRIVESLIST		406
#define PREF_FORBIDDENDRIVES		407
#define PREF_FORBIDDENDRIVESLIST	408
#define PREF_CANTCHANGEPREF		409

// General preferences dialog box
#define PREF_BEGINNER			501
#define PREF_ONEWINDOW			502
#define PREF_EDITFULLPATH		503
#define PREF_EDITSAVEBACKUP		504
#define PREF_INDENTSIZE			505
#define PREF_CONFIRMQUIT		506
#define PREF_SKIPSPLASH			507
#define PREF_ADDSUFFIX			508
#define PREF_EDITSPACESTOTABS		509
#define PREF_OPENBRACESAMELINE		510
#define PREF_EDITSPACESPERTAB		511
#define PREF_NORECENTFILES		512
#define PREF_USELASTACTIVEDIRECTORY	513

// Appearance preferences dialog box
#define PREF_EDITFONTNAME		601
#define PREF_EDITFONTSIZE		602
#define PREF_EDITCHANGEFONT		603
#define PREF_EDITCOLOUR			604
#define PREF_BEGINFULLSCREEN		605
#define PREF_ADVFULLSCREEN		606
#define PREF_EDITTEXTROWS		607
#define PREF_EDITTEXTCOLS		608
#define PREF_CARETWIDTH			609
#define PREF_DLGFONTSIZE		610
#define PREF_BUTTONSHORTCUT		611

// Run preferemces dialog box
#define PREF_RUNFONTNAME		701
#define PREF_RUNFONTSIZE		702
#define PREF_RUNCHANGEFONT		703
#define PREF_RUNPLAINCONSOLE		704
#define PREF_RUNFULLSCREEN		705
#define PREF_RUNTEXTROWS		706
#define PREF_RUNTEXTCOLS		707
#define PREF_RUNAPPLETXSIZE		708
#define PREF_RUNAPPLETYSIZE		709

// Java preferences dialog box
#define PREF_JAVAADDCLASSPATH		751
#define PREF_JAVAJIKESOPTION		752
#define PREF_JAVAJVMOPTION		753
#define PREF_JAVAAPPLVIEWOPTION		754
#define PREF_JAVAALTJVM			755
#define PREF_JAVAALTJVMBTN		756
#define PREF_JAVAALTAPPLVIEW		757
#define PREF_JAVAALTAPPLVIEWBTN		758
#define PREF_JAVAALTCLASSLIB		759
#define PREF_JAVAALTCLASSLIBBTN		760
#define PREF_JAVAUSEJIT			761

// Printing preferences dialog box
#define PREF_PRINTFONTNAME		801
#define PREF_PRINTFONTSIZE		802
#define PREF_PRINTCHANGEFONT		803
#define PREF_PRINTUSERNAME		804
#define PREF_PRINTBOLD			805
#define PREF_PRINTITAL			806
#define PREF_PRINTHEADER		807
#define PRINT_PRINTPRINTUSERNAME	808
#define PREF_PRINTLINENUMBER		809
#define PREF_PRINTTWOUP			810
#define PREF_PRINTBORDER		811
// Margins *must* be grouped together
#define PREF_PRINTLEFTMARG		812
#define PREF_PRINTRIGHTMARG		813
#define PREF_PRINTTOPMARG		814
#define PREF_PRINTBOTTOMMARG		815
#define FIRST_MARGIN			PREF_PRINTLEFTMARG
#define LAST_MARGIN			PREF_PRINTBOTTOMMARG
#define PREF_PRINTHDRFONTNAME		816
#define PREF_PRINTHDRFONTSIZE		817
#define PREF_PRINTHDRCHANGEFONT		818

// Printing status dialog box
#define PRINT_JOBNAME			901
#define PRINT_PAGENUMBER		902

// Print dialog box
#define PRINT_BOLD_KEYWORDS		903
#define PRINT_ITAL_IDENTS		904
#define PRINT_FULL_PATHNAME		905
#define PRINT_TWO_UP			906
#define PRINT_LINE_NUMBERS		907
#define PRINT_BORDERS			908
*/
